CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE "" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" TEXT NOT NULL);
CREATE TABLE "scale2_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "cooling_compressor_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "heater_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "sensor_humidity_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "circulating_air_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "sensor_temperature_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "exhaust_air_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE 'config' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "scale1_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "light_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "uv_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE 'current_values' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "humidifier_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "dehumidifier_status" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE 'agingtable_dryaging2' ( 'id' INTEGER DEFAULT 0 PRIMARY KEY NOT NULL , 'modus' INTEGER, 'setpoint_humidity' INTEGER, 'setpoint_temperature' INTEGER, 'circulation_air_duration' INTEGER,'circulation_air_period' INTEGER, 'exhaust_air_duration' INTEGER, 'exhaust_air_period' INTEGER, 'days' INTEGER DEFAULT 0 NOT NULL, 'comment' TEXT);
CREATE TABLE 'agingtable_salami' ( 'id' INTEGER DEFAULT 0 PRIMARY KEY NOT NULL , 'modus' INTEGER, 'setpoint_humidity' INTEGER, 'setpoint_temperature' INTEGER, 'circulation_air_duration' INTEGER,'circulation_air_period' INTEGER, 'exhaust_air_duration' INTEGER, 'exhaust_air_period' INTEGER, 'days' INTEGER DEFAULT 0 NOT NULL, 'comment' TEXT);
CREATE TABLE "sensor_temperature_meat1_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "sensor_temperature_meat2_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "sensor_temperature_meat3_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE "sensor_temperature_meat4_data" ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL, key TEXT DEFAULT 0 NOT NULL);
CREATE TABLE 'debug' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, last_change INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE 'agingtables' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL,'name' TEXT DEFAULT 0 NOT NULL);
CREATE TABLE 'system' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL,'value' TEXT DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL DEFAULT 0);
CREATE TABLE 'agingtable_dryaging1' ('id' INTEGER DEFAULT 0 PRIMARY KEY NOT NULL ,'modus' INTEGER, "setpoint_humidity" INTEGER, "setpoint_temperature" INTEGER, "circulation_air_duration" INTEGER,"circulation_air_period" INTEGER, "exhaust_air_duration" INTEGER, "exhaust_air_period" INTEGER, "days" INTEGER DEFAULT 0 NOT NULL, 'comment' TEXT);
CREATE TABLE 'scale1_settings' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE 'scale2_settings' ('id' INTEGER DEFAULT 0 PRIMARY KEY AUTOINCREMENT NOT NULL, 'key' TEXT DEFAULT 0 NOT NULL, 'value' REAL DEFAULT 0 NOT NULL, 'last_change' INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE "email_server" (
    "server" TEXT NOT NULL,
    "user" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "starttls" INTEGER,
    "from_mail" TEXT NOT NULL
);
CREATE TABLE "messenger" (
    "id" INTEGER NOT NULL,
    "exception" TEXT NOT NULL,
    "message_type" TEXT NOT NULL,
    "active" INTEGER
);
CREATE TABLE "alarm" (
    "exception" TEXT NOT NULL,
    "alarm_length" INTEGER NOT NULL DEFAULT (1),
    "alarm_duration" INTEGER NOT NULL DEFAULT (1)
);
CREATE TABLE email_recipient (
    "id" INTEGER NOT NULL,
    "to_mail" TEXT NOT NULL,
    "active" INTEGER
);
CREATE TABLE nfs_backup (
    "nfsvol" TEXT,
    "subdir" TEXT,
    "nfsmount" TEXT,
    "backup_path" TEXT,
    "number_of_backups" INTEGER,
    "backup_name" TEXT,
    "active" INTEGER,
    "nfsopt" TEXT
);
