# /usr/share/doc/lighttpd/authentication.txt.gz

server.modules                += ( "mod_auth" )

auth.backend                    = "htdigest"
auth.backend.htdigest.userfile     = "/var/.htcredentials"

auth.require                    = ( "/settings.php" =>
                                   (
                                    "method" => "digest",
                                    "realm" => "Pi-Ager",
                                    "require" => "user=pi-ager"
                                   ),
                                    "/admin.php" =>
                                   (
                                    "method"  => "digest",
                                    "realm"   => "Pi-Ager",
                                    "require" => "valid-user" 
                                    ),
                                    "/webcam.php" =>
                                   (
                                    "method"  => "digest",
                                    "realm"   => "Pi-Ager",
                                    "require" => "valid-user" 
                                    ),
                                    "/notification.php" =>
                                   (
                                    "method"  => "digest",
                                    "realm"   => "Pi-Ager",
                                    "require" => "valid-user" 
                                    )
                                  )
